# Generated by Django 6.0.6 on 2026-07-03 15:06

import apps.learning.models
import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('words_per_session', models.PositiveSmallIntegerField(default=10)),
                ('study_weekdays', models.JSONField(default=apps.learning.models.default_weekdays)),
                ('morning_time', models.TimeField(default=datetime.time(7, 0))),
                ('exam_time', models.TimeField(default=datetime.time(20, 0))),
                ('audio_enabled', models.BooleanField(default=True)),
                ('audio_repeat', models.PositiveSmallIntegerField(default=2)),
                ('timezone', models.CharField(default='Asia/Tashkent', max_length=40)),
                ('language', models.CharField(default='uz', max_length=8)),
                ('onboarded', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('current_word_order', models.PositiveSmallIntegerField(default=0)),
                ('current_book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.book')),
                ('current_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.unit')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learning_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Learning profile',
                'verbose_name_plural': 'Learning profiles',
            },
        ),
    ]
