# Generated by Django 6.0.6 on 2026-07-04 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('learning', '0002_dailysession_sessionword_dailysession_words_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_type', models.CharField(choices=[('en_uz', 'EN→UZ'), ('uz_en', 'UZ→EN'), ('def_word', 'Definition')], max_length=10)),
                ('poll_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('options', models.JSONField(default=list)),
                ('correct_option', models.PositiveSmallIntegerField()),
                ('chosen_option', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('daily_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='learning.dailysession')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.word')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
