# Generated by Django 6.0.6 on 2026-07-04 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_examquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysession',
            name='pre_exam_nudged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailysession',
            name='study_nudged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='learningprofile',
            name='nudges_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
