# Generated by Django 6.0.6 on 2026-07-12 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_learnedword'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningprofile',
            name='en_voice',
            field=models.CharField(default='en-US-AriaNeural', max_length=40),
        ),
        migrations.AddField(
            model_name='learningprofile',
            name='uz_voice',
            field=models.CharField(default='uz-UZ-MadinaNeural', max_length=40),
        ),
    ]
