# Generated by Django 6.0.6 on 2026-07-13 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_learningprofile_en_voice_learningprofile_uz_voice'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysession',
            name='exam_stage',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='learningprofile',
            name='speaking_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
