# Generated by Django 6.0.6 on 2026-07-18 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_dailysession_exam_stage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysession',
            name='completed_late',
            field=models.BooleanField(default=False),
        ),
    ]
