# Generated by Django 6.0.6 on 2026-07-04 09:07

import apps.quiz.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupQuizSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chat_id', models.BigIntegerField(db_index=True)),
                ('unit_ids', models.JSONField(default=apps.quiz.models._empty_list)),
                ('question_types', models.JSONField(default=apps.quiz.models._empty_list)),
                ('question_count', models.PositiveSmallIntegerField(default=10)),
                ('interval_seconds', models.PositiveSmallIntegerField(default=20)),
                ('status', models.CharField(choices=[('configuring', 'Configuring'), ('running', 'Running'), ('finished', 'Finished'), ('aborted', 'Aborted')], default='configuring', max_length=12)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.book')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='GroupQuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('question_type', models.CharField(max_length=10)),
                ('poll_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('options', models.JSONField(default=apps.quiz.models._empty_list)),
                ('correct_option', models.PositiveSmallIntegerField()),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.word')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.groupquizsession')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='GroupQuizParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('telegram_id', models.BigIntegerField()),
                ('username', models.CharField(blank=True, default='', max_length=64)),
                ('full_name', models.CharField(blank=True, default='', max_length=128)),
                ('correct_count', models.PositiveSmallIntegerField(default=0)),
                ('total_time', models.FloatField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='quiz.groupquizsession')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('session', 'telegram_id'), name='uniq_session_participant')],
            },
        ),
    ]
