# Generated by Django 6.0.6 on 2026-07-04 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupquizsession',
            name='started_by',
        ),
        migrations.AddField(
            model_name='groupquizsession',
            name='started_by_telegram_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
