# Generated by Django 6.0.6 on 2026-07-07 11:05

import apps.quiz.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_unit_telegram_audio_file_id'),
        ('quiz', '0002_remove_groupquizsession_started_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_telegram_id', models.BigIntegerField(db_index=True)),
                ('unit_ids', models.JSONField(default=apps.quiz.models._empty_list)),
                ('question_types', models.JSONField(default=apps.quiz.models._empty_list)),
                ('question_count', models.PositiveSmallIntegerField(default=10)),
                ('interval_seconds', models.PositiveSmallIntegerField(default=30)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.book')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
