# Generated by Django 4.2.1 on 2023-05-10 08:09

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(help_text='Foydalanuvchi ismi', max_length=100, verbose_name='Ism')),
                ('last_name', models.CharField(blank=True, default=None, help_text='Foydalanuvchi familiyasi', max_length=100, null=True, verbose_name='Familiya')),
                ('phone_number', models.BigIntegerField(help_text='998911234567 formatda kiriting.', unique=True, validators=[django.core.validators.RegexValidator(regex='^(\\+?)998(90|91|93|94|95|97|98|99|33|88|77)[0-9]{7}$')], verbose_name='Telefon raqam')),
                ('password', models.CharField(max_length=128, verbose_name='Parol')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
            },
        ),
    ]
