# Generated by Django 6.0.6 on 2026-07-03 10:27

import apps.catalog.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveSmallIntegerField(unique=True, verbose_name='Number')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('level', models.CharField(blank=True, max_length=8)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='images/books/covers/')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='books/pdf/')),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'ordering': ('number',),
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveSmallIntegerField()),
                ('title', models.CharField(blank=True, max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='catalog.book')),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
                'ordering': ('book', 'number'),
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('en', models.CharField(max_length=100, verbose_name='English')),
                ('uz', models.CharField(max_length=255, verbose_name='Uzbek')),
                ('part_of_speech', models.CharField(blank=True, max_length=20)),
                ('pronunciation', models.CharField(blank=True, max_length=100)),
                ('definition', models.TextField(blank=True)),
                ('example', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.catalog.models.word_image_upload_to)),
                ('audio_en', models.FileField(blank=True, null=True, upload_to=apps.catalog.models.word_audio_upload_to)),
                ('audio_uz', models.FileField(blank=True, null=True, upload_to=apps.catalog.models.word_audio_upload_to)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='catalog.unit')),
            ],
            options={
                'verbose_name': 'Word',
                'verbose_name_plural': 'Words',
                'ordering': ('unit', 'order'),
            },
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.UniqueConstraint(fields=('book', 'number'), name='uniq_book_unit'),
        ),
        migrations.AddIndex(
            model_name='word',
            index=models.Index(fields=['en'], name='catalog_wor_en_072646_idx'),
        ),
        migrations.AddConstraint(
            model_name='word',
            constraint=models.UniqueConstraint(fields=('unit', 'en'), name='uniq_unit_word'),
        ),
    ]
