# Generated by Django 6.0.6 on 2026-07-07 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='telegram_file_id',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
