# Generated by Django 6.0.6 on 2026-07-07 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_book_telegram_file_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='telegram_audio_file_id',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
